name: caddy
services:
  caddy:
    image: ghcr.io/dboxed/dboxed-lb-caddy:{{ .CaddyVersion }}
    {{- if or (eq .CaddyVersion "nightly") (eq .CaddyVersion "latest") }}
    pull_policy: always
    {{- end }}
    restart: unless-stopped
    command:
      - caddy
      - run
      - --config=/etc/caddy/Caddyfile
      - --adapter=caddyfile
      - --watch
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - type: content
        target: /etc/caddy/Caddyfile
        x-content: |
          {{- .Caddyfile | nindent 10 }}
